---
# Source: autopilot-daemon/templates/rbac/serviceaccount.yaml
kind: Namespace
apiVersion: v1
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: autopilot
spec:
  finalizers:
  - kubernetes
---
# Source: autopilot-daemon/templates/rbac/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: autopilot
  namespace: autopilot
---
# Source: autopilot-daemon/templates/rbac/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: autopilot
  namespace: autopilot
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "get", "patch", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["list", "get"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["list", "get", "create", "delete"]
---
# Source: autopilot-daemon/templates/rbac/serviceaccount.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: autopilot 
  namespace: autopilot
subjects:
- kind: ServiceAccount
  name: autopilot 
  namespace: autopilot 
roleRef: 
  kind: ClusterRole
  name: autopilot 
  apiGroup: rbac.authorization.k8s.io
